blueprint:
  name: Paralelo Virtual (sem loop)
  description: Acende/Apaga todos os switchs/lights do grupo simultaneamente, sem loop
  domain: automation
  input:
    entrada_switchs:
      name: Escolha os pontos de Iluminação
      selector:
        entity:
          domain:
            - switch
            - light
          multiple: true

trigger:
  - platform: state
    entity_id: !input entrada_switchs

# 🔒 Evita loop e mudanças falsas
condition:
  - condition: template
    value_template: >
      {{ trigger.from_state is not none and
         trigger.to_state is not none and
         trigger.from_state.state != trigger.to_state.state }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input entrada_switchs

      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input entrada_switchs

mode: queued
max: 5
