blueprint:
  name: Paralelo Virtual (lock selecionável)
  description: Paralelo virtual sem loop, com lock dinâmico
  domain: automation

  input:
    entrada_switchs:
      name: Interruptores / Luzes
      selector:
        entity:
          domain:
            - switch
            - light
          multiple: true

    lock_helper:
      name: Lock de proteção (input_boolean)
      description: Crie um helper input_boolean por circuito
      selector:
        entity:
          domain:
            - input_boolean

trigger:
  - platform: state
    entity_id: !input entrada_switchs

condition:
  - condition: state
    entity_id: !input lock_helper
    state: "off"

  - condition: template
    value_template: >
      {{ trigger.from_state is not none and
         trigger.to_state is not none and
         trigger.from_state.state != trigger.to_state.state }}

action:
  # 🔒 Lock
  - service: input_boolean.turn_on
    target:
      entity_id: !input lock_helper

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input entrada_switchs

      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input entrada_switchs

  # 🔓 Unlock rápido
  - delay:
      milliseconds: 300

  - service: input_boolean.turn_off
    target:
      entity_id: !input lock_helper

mode: restart
