blueprint:
  name: Paralelo Virtual
  description: Paralelo virtual sem helper e sem loop
  domain: automation

  input:
    entrada_switchs:
      name: Interruptores / Luzes
      selector:
        entity:
          domain:
            - switch
            - light
          multiple: true

trigger:
  - platform: state
    entity_id: !input entrada_switchs

action:
  - variables:
      origem: "{{ trigger.entity_id }}"
      estado: "{{ states(trigger.entity_id) }}"
      destinos: >
        {{ expand(!input entrada_switchs)
           | selectattr('entity_id', '!=', trigger.entity_id)
           | map(attribute='entity_id')
           | list }}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ estado == 'on' }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: "{{ destinos }}"

      - conditions:
          - condition: template
            value_template: "{{ estado == 'off' }}"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ destinos }}"

mode: queued
